#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FiveMinuteMeeting.Droid.Resource", IsApplication=true)]

namespace FiveMinuteMeeting.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circleColor = global::FiveMinuteMeeting.Droid.Resource.Attribute.circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circularProgressBarStyle = global::FiveMinuteMeeting.Droid.Resource.Attribute.circularProgressBarStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_gravity = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_indeterminate_interval = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_marker_progress = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_background_color = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_progress_color = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.circular_stroke_width = global::FiveMinuteMeeting.Droid.Resource.Attribute.circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate = global::FiveMinuteMeeting.Droid.Resource.Attribute.indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.indeterminate_interval = global::FiveMinuteMeeting.Droid.Resource.Attribute.indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.innerSize = global::FiveMinuteMeeting.Droid.Resource.Attribute.innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.max = global::FiveMinuteMeeting.Droid.Resource.Attribute.max;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinned = global::FiveMinuteMeeting.Droid.Resource.Attribute.pinned;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.pinnedDrawable = global::FiveMinuteMeeting.Droid.Resource.Attribute.pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progress = global::FiveMinuteMeeting.Droid.Resource.Attribute.progress;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressButtonStyle = global::FiveMinuteMeeting.Droid.Resource.Attribute.progressButtonStyle;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.progressColor = global::FiveMinuteMeeting.Droid.Resource.Attribute.progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.shadowDrawable = global::FiveMinuteMeeting.Droid.Resource.Attribute.shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Attribute.unpinnedDrawable = global::FiveMinuteMeeting.Droid.Resource.Attribute.unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_circle_color = global::FiveMinuteMeeting.Droid.Resource.Color.progress_default_circle_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.progress_default_progress_color = global::FiveMinuteMeeting.Droid.Resource.Color.progress_default_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_background_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_background_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_background_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_background_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_background_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_dark_disabled = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_dark_disabled;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_disabled_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_bright_foreground_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_bright_foreground_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_disabled_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_dim_foreground_disabled_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_dim_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_dim_foreground_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_dim_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_highlighted_text_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_highlighted_text_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_highlighted_text_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_hint_foreground_holo_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_hint_foreground_holo_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_hint_foreground_holo_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_bright = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_blue_bright;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_blue_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_blue_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_blue_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_green_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_green_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_green_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_orange_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_orange_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_orange_light;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_purple = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_purple;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_dark = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_red_dark;
			global::com.refractored.monodroidtoolkit.Resource.Color.refractored_holo_red_light = global::FiveMinuteMeeting.Droid.Resource.Color.refractored_holo_red_light;
			global::com.refractored.monodroidtoolkit.Resource.Dimension.progress_inner_size = global::FiveMinuteMeeting.Droid.Resource.Dimension.progress_inner_size;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_pinned = global::FiveMinuteMeeting.Droid.Resource.Drawable.pin_progress_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_shadow = global::FiveMinuteMeeting.Droid.Resource.Drawable.pin_progress_shadow;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.pin_progress_unpinned = global::FiveMinuteMeeting.Droid.Resource.Drawable.pin_progress_unpinned;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_normal_holo = global::FiveMinuteMeeting.Droid.Resource.Drawable.scrubber_control_normal_holo;
			global::com.refractored.monodroidtoolkit.Resource.Drawable.scrubber_control_pressed_holo = global::FiveMinuteMeeting.Droid.Resource.Drawable.scrubber_control_pressed_holo;
			global::com.refractored.monodroidtoolkit.Resource.Id.bottom = global::FiveMinuteMeeting.Droid.Resource.Id.bottom;
			global::com.refractored.monodroidtoolkit.Resource.Id.center = global::FiveMinuteMeeting.Droid.Resource.Id.center;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_horizontal = global::FiveMinuteMeeting.Droid.Resource.Id.center_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.center_vertical = global::FiveMinuteMeeting.Droid.Resource.Id.center_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip = global::FiveMinuteMeeting.Droid.Resource.Id.clip;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_horizontal = global::FiveMinuteMeeting.Droid.Resource.Id.clip_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.clip_vertical = global::FiveMinuteMeeting.Droid.Resource.Id.clip_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.end = global::FiveMinuteMeeting.Droid.Resource.Id.end;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill = global::FiveMinuteMeeting.Droid.Resource.Id.fill;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_horizontal = global::FiveMinuteMeeting.Droid.Resource.Id.fill_horizontal;
			global::com.refractored.monodroidtoolkit.Resource.Id.fill_vertical = global::FiveMinuteMeeting.Droid.Resource.Id.fill_vertical;
			global::com.refractored.monodroidtoolkit.Resource.Id.left = global::FiveMinuteMeeting.Droid.Resource.Id.left;
			global::com.refractored.monodroidtoolkit.Resource.Id.right = global::FiveMinuteMeeting.Droid.Resource.Id.right;
			global::com.refractored.monodroidtoolkit.Resource.Id.start = global::FiveMinuteMeeting.Droid.Resource.Id.start;
			global::com.refractored.monodroidtoolkit.Resource.Id.top = global::FiveMinuteMeeting.Droid.Resource.Id.top;
			global::com.refractored.monodroidtoolkit.Resource.Integer.circular_indeterminent_interval = global::FiveMinuteMeeting.Droid.Resource.Integer.circular_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Integer.progressbutton_indeterminent_interval = global::FiveMinuteMeeting.Droid.Resource.Integer.progressbutton_indeterminent_interval;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBar = global::FiveMinuteMeeting.Droid.Resource.Style.CircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Style.CircularProgressBarLight = global::FiveMinuteMeeting.Droid.Resource.Style.CircularProgressBarLight;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton = global::FiveMinuteMeeting.Droid.Resource.Style.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Style.ProgressButton_Pin = global::FiveMinuteMeeting.Droid.Resource.Style.ProgressButton_Pin;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_gravity = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_gravity;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_marker_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_background_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_progress_color = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_progress_color;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width = global::FiveMinuteMeeting.Droid.Resource.Styleable.HoloCircularProgressBar_circular_stroke_width;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_clickable = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_android_clickable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_focusable = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_android_focusable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_android_selectableItemBackground = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_android_selectableItemBackground;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_circleColor = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_circleColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_indeterminate;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_indeterminate_interval = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_indeterminate_interval;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_innerSize = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_innerSize;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_max = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_max;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinned = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_pinned;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_pinnedDrawable = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_pinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progress = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_progress;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_progressColor = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_progressColor;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_shadowDrawable = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_shadowDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.ProgressButton_unpinnedDrawable = global::FiveMinuteMeeting.Droid.Resource.Styleable.ProgressButton_unpinnedDrawable;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme = global::FiveMinuteMeeting.Droid.Resource.Styleable.Theme;
			global::com.refractored.monodroidtoolkit.Resource.Styleable.Theme_circularProgressBarStyle = global::FiveMinuteMeeting.Droid.Resource.Styleable.Theme_circularProgressBarStyle;
			global::Microsoft.Office365.OAuth.Resource.String.ApplicationName = global::FiveMinuteMeeting.Droid.Resource.String.ApplicationName;
			global::Microsoft.Office365.OAuth.Resource.String.Hello = global::FiveMinuteMeeting.Droid.Resource.String.Hello;
			global::Refractored.Xam.Messages.Resource.String.ApplicationName = global::FiveMinuteMeeting.Droid.Resource.String.ApplicationName;
			global::Refractored.Xam.Messages.Resource.String.Hello = global::FiveMinuteMeeting.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int circleColor = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int circularProgressBarStyle = 2130771990;
			
			// aapt resource value: 0x7f01000e
			public const int circular_gravity = 2130771982;
			
			// aapt resource value: 0x7f010014
			public const int circular_indeterminate = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int circular_indeterminate_interval = 2130771989;
			
			// aapt resource value: 0x7f010011
			public const int circular_marker_progress = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int circular_progress = 2130771984;
			
			// aapt resource value: 0x7f010013
			public const int circular_progress_background_color = 2130771987;
			
			// aapt resource value: 0x7f010012
			public const int circular_progress_color = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int circular_stroke_width = 2130771983;
			
			// aapt resource value: 0x7f01000c
			public const int indeterminate = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int indeterminate_interval = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int innerSize = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int max = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int pinned = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int pinnedDrawable = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int progress = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int progressButtonStyle = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int progressColor = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int shadowDrawable = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int unpinnedDrawable = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040024
			public const int blue = 2130968612;
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int progress_default_circle_color = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int progress_default_progress_color = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int refractored_background_dark = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int refractored_background_holo_dark = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int refractored_background_holo_light = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int refractored_background_light = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int refractored_bright_foreground_dark = 2130968584;
			
			// aapt resource value: 0x7f04000a
			public const int refractored_bright_foreground_dark_disabled = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int refractored_bright_foreground_disabled_holo_dark = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int refractored_bright_foreground_disabled_holo_light = 2130968592;
			
			// aapt resource value: 0x7f04000d
			public const int refractored_bright_foreground_holo_dark = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int refractored_bright_foreground_holo_light = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int refractored_bright_foreground_light = 2130968585;
			
			// aapt resource value: 0x7f040012
			public const int refractored_dim_foreground_disabled_holo_dark = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int refractored_dim_foreground_disabled_holo_light = 2130968597;
			
			// aapt resource value: 0x7f040011
			public const int refractored_dim_foreground_holo_dark = 2130968593;
			
			// aapt resource value: 0x7f040014
			public const int refractored_dim_foreground_holo_light = 2130968596;
			
			// aapt resource value: 0x7f040017
			public const int refractored_highlighted_text_holo_dark = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int refractored_highlighted_text_holo_light = 2130968600;
			
			// aapt resource value: 0x7f040013
			public const int refractored_hint_foreground_holo_dark = 2130968595;
			
			// aapt resource value: 0x7f040016
			public const int refractored_hint_foreground_holo_light = 2130968598;
			
			// aapt resource value: 0x7f040022
			public const int refractored_holo_blue_bright = 2130968610;
			
			// aapt resource value: 0x7f04001c
			public const int refractored_holo_blue_dark = 2130968604;
			
			// aapt resource value: 0x7f040019
			public const int refractored_holo_blue_light = 2130968601;
			
			// aapt resource value: 0x7f04001d
			public const int refractored_holo_green_dark = 2130968605;
			
			// aapt resource value: 0x7f04001a
			public const int refractored_holo_green_light = 2130968602;
			
			// aapt resource value: 0x7f040021
			public const int refractored_holo_orange_dark = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int refractored_holo_orange_light = 2130968608;
			
			// aapt resource value: 0x7f04001f
			public const int refractored_holo_purple = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int refractored_holo_red_dark = 2130968606;
			
			// aapt resource value: 0x7f04001b
			public const int refractored_holo_red_light = 2130968603;
			
			// aapt resource value: 0x7f040023
			public const int white = 2130968611;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_default_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_size = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int progress_inner_size = 2131034115;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int pin_progress_pinned = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int pin_progress_shadow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pin_progress_unpinned = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int scrubber_control_normal_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int scrubber_control_pressed_holo = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001c
			public const int action_edit = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int action_save = 2131361821;
			
			// aapt resource value: 0x7f0a0000
			public const int bottom = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int center = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int center_horizontal = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int center_vertical = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int clip = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int clip_horizontal = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int clip_vertical = 2131361798;
			
			// aapt resource value: 0x7f0a0018
			public const int email = 2131361816;
			
			// aapt resource value: 0x7f0a0007
			public const int end = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int fill = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int fill_horizontal = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int fill_vertical = 2131361802;
			
			// aapt resource value: 0x7f0a0015
			public const int first_name = 2131361813;
			
			// aapt resource value: 0x7f0a0010
			public const int imageView = 2131361808;
			
			// aapt resource value: 0x7f0a0016
			public const int last_name = 2131361814;
			
			// aapt resource value: 0x7f0a000b
			public const int left = 2131361803;
			
			// aapt resource value: 0x7f0a001a
			public const int phone = 2131361818;
			
			// aapt resource value: 0x7f0a0013
			public const int photo = 2131361811;
			
			// aapt resource value: 0x7f0a001b
			public const int refresher = 2131361819;
			
			// aapt resource value: 0x7f0a000c
			public const int right = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int start = 2131361805;
			
			// aapt resource value: 0x7f0a0011
			public const int textView = 2131361809;
			
			// aapt resource value: 0x7f0a0014
			public const int textView1 = 2131361812;
			
			// aapt resource value: 0x7f0a0012
			public const int textView2 = 2131361810;
			
			// aapt resource value: 0x7f0a0017
			public const int textView3 = 2131361815;
			
			// aapt resource value: 0x7f0a0019
			public const int textView4 = 2131361817;
			
			// aapt resource value: 0x7f0a000e
			public const int top = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int view1 = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080001
			public const int circular_indeterminent_interval = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int progressbutton_indeterminent_interval = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contact = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Detail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Detail_Demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int main = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int CircularProgressBar = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int CircularProgressBarLight = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ProgressButton = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int ProgressButton_Pin = 2131099652;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			public static int[] HoloCircularProgressBar = new int[] {
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 0
			public const int HoloCircularProgressBar_circular_gravity = 0;
			
			// aapt resource value: 6
			public const int HoloCircularProgressBar_circular_indeterminate = 6;
			
			// aapt resource value: 7
			public const int HoloCircularProgressBar_circular_indeterminate_interval = 7;
			
			// aapt resource value: 3
			public const int HoloCircularProgressBar_circular_marker_progress = 3;
			
			// aapt resource value: 2
			public const int HoloCircularProgressBar_circular_progress = 2;
			
			// aapt resource value: 5
			public const int HoloCircularProgressBar_circular_progress_background_color = 5;
			
			// aapt resource value: 4
			public const int HoloCircularProgressBar_circular_progress_color = 4;
			
			// aapt resource value: 1
			public const int HoloCircularProgressBar_circular_stroke_width = 1;
			
			public static int[] ProgressButton = new int[] {
					16842970,
					16842981,
					16843534,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int ProgressButton_android_clickable = 1;
			
			// aapt resource value: 0
			public const int ProgressButton_android_focusable = 0;
			
			// aapt resource value: 2
			public const int ProgressButton_android_selectableItemBackground = 2;
			
			// aapt resource value: 5
			public const int ProgressButton_circleColor = 5;
			
			// aapt resource value: 12
			public const int ProgressButton_indeterminate = 12;
			
			// aapt resource value: 13
			public const int ProgressButton_indeterminate_interval = 13;
			
			// aapt resource value: 10
			public const int ProgressButton_innerSize = 10;
			
			// aapt resource value: 4
			public const int ProgressButton_max = 4;
			
			// aapt resource value: 11
			public const int ProgressButton_pinned = 11;
			
			// aapt resource value: 7
			public const int ProgressButton_pinnedDrawable = 7;
			
			// aapt resource value: 3
			public const int ProgressButton_progress = 3;
			
			// aapt resource value: 6
			public const int ProgressButton_progressColor = 6;
			
			// aapt resource value: 9
			public const int ProgressButton_shadowDrawable = 9;
			
			// aapt resource value: 8
			public const int ProgressButton_unpinnedDrawable = 8;
			
			public static int[] Theme = new int[] {
					2130771990};
			
			// aapt resource value: 0
			public const int Theme_circularProgressBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
